language: bash

services:
  - docker

env:
  global:
    - IMAGE_NAME=${DOCKERHUB_USER}/swagger-ui-multi-source
    - IMAGE_NAME_TAGGED=${DOCKERHUB_USER}/wahlzeit:${TRAVIS_TAG}

script:
  - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}'
  - docker build -t ${IMAGE_NAME} .

deploy:
  - provider: script
    script:
      docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PW} && docker push ${IMAGE_NAME}
    on:
      branch: master

  - provider: script
    script: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PW} && docker tag ${IMAGE_NAME} ${IMAGE_NAME_TAGGED} && docker push ${IMAGE_NAME_TAGGED}
    on:
      tags: true