version: '3.7'

services:
  swagger-ui:
    build:
      context: ../
    environment:
      - SWAGGER_RESOURCE_1=test1;test1:8080/api;2.0
      - SWAGGER_RESOURCE_2=test2;test2:8080/api;2.0
    ports:
      - 8080:8080